name = "fslides-site"
main = "src/index.js"
compatibility_date = "2026-07-01"

routes = [
  { pattern = "fslides.dev", custom_domain = true },
  { pattern = "www.fslides.dev", custom_domain = true },
  { pattern = "decks.fslides.dev", custom_domain = true }
]

[assets]
directory = "_site"

[[r2_buckets]]
binding = "DECKS"
bucket_name = "fslides-decks"
